version: '3.8'

services:
  postgres:
    container_name: toimi_postgres
    hostname: postgres
    image: postgres:13.3
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - 5432:5432

  app:
    build: .
    container_name: toimi_app
    hostname: app
    image: app
    environment:
      - PG_URL=postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-pass}@${POSTGRES_DB:-postgres}:5432/${POSTGRES_DB:-postgres}
      - PORT=${HTTP_PORT:-8080}
    ports:
      - 8080:8080
    depends_on:
      - postgres